# Generated by Django 6.0.3 on 2026-05-11 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('interval_minutes', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Taken', 'Taken'), ('Missed', 'Missed')], default='Pending', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('next_reminder_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('countdown_seconds', models.IntegerField()),
                ('total_seconds', models.IntegerField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
