# Generated by Django 6.0.3 on 2026-05-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinereminder',
            name='dosage',
            field=models.CharField(blank=True, help_text='Optional dosage instructions', max_length=100),
        ),
        migrations.AddField(
            model_name='medicinereminder',
            name='repeat',
            field=models.BooleanField(default=True, help_text='Repeat this reminder after each interval'),
        ),
        migrations.AddField(
            model_name='medicinereminder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medicinereminder',
            name='countdown_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicinereminder',
            name='interval_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='medicinereminder',
            name='total_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
