# Generated by Django 6.0.3 on 2026-05-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0002_medicinereminder_dosage_medicinereminder_repeat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinereminder',
            name='alarm_time',
            field=models.CharField(blank=True, help_text='Alarm time in hh:mm AM/PM format', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicinereminder',
            name='interval_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicinereminder',
            name='repeat',
            field=models.BooleanField(default=True, help_text='Repeat this reminder each day at the alarm time'),
        ),
    ]
